export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';

export const STORAGE_KEYS = {
  AUTH_TOKEN: 'admin_auth_token',
  REFRESH_TOKEN: 'admin_refresh_token',
  USER_DATA: 'admin_user_data',
  THEME: 'admin_theme',
} as const;

export const FUEL_PRICES = {
  PETROL: 65, // GMD per liter
  DIESEL: 68, // GMD per liter
} as const;

export const LOW_STOCK_THRESHOLD = 1000; // liters

export const QR_EXPIRY_HOURS = {
  SUBSIDY: 24 * 30, // 30 days
  PAID: 24, // 24 hours
} as const;

export const ADMIN_PERMISSIONS = {
  // Beneficiary Management
  VIEW_BENEFICIARIES: 'VIEW_BENEFICIARIES',
  VERIFY_BENEFICIARIES: 'VERIFY_BENEFICIARIES',
  MANAGE_ALLOCATIONS: 'MANAGE_ALLOCATIONS',
  
  // Customer Management
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  
  // Station Management
  VIEW_STATIONS: 'VIEW_STATIONS',
  MANAGE_STATIONS: 'MANAGE_STATIONS',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  
  // Attendant Management
  VIEW_ATTENDANTS: 'VIEW_ATTENDANTS',
  MANAGE_ATTENDANTS: 'MANAGE_ATTENDANTS',
  
  // Transactions
  VIEW_TRANSACTIONS: 'VIEW_TRANSACTIONS',
  AUDIT_TRANSACTIONS: 'AUDIT_TRANSACTIONS',
  
  // Payments
  VIEW_PAYMENTS: 'VIEW_PAYMENTS',
  MANAGE_PAYMENTS: 'MANAGE_PAYMENTS',
  PROCESS_REFUNDS: 'PROCESS_REFUNDS',
  
  // Reports
  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',
  
  // Settings
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  MANAGE_ADMINS: 'MANAGE_ADMINS',
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: Object.values(ADMIN_PERMISSIONS),
  DEPARTMENT_OFFICER: [
    ADMIN_PERMISSIONS.VIEW_BENEFICIARIES,
    ADMIN_PERMISSIONS.VERIFY_BENEFICIARIES,
    ADMIN_PERMISSIONS.MANAGE_ALLOCATIONS,
    ADMIN_PERMISSIONS.VIEW_TRANSACTIONS,
    ADMIN_PERMISSIONS.VIEW_REPORTS,
    ADMIN_PERMISSIONS.EXPORT_REPORTS,
  ],
  STATION_MANAGER: [
    ADMIN_PERMISSIONS.VIEW_STATIONS,
    ADMIN_PERMISSIONS.MANAGE_STATIONS,
    ADMIN_PERMISSIONS.MANAGE_INVENTORY,
    ADMIN_PERMISSIONS.VIEW_ATTENDANTS,
    ADMIN_PERMISSIONS.MANAGE_ATTENDANTS,
    ADMIN_PERMISSIONS.VIEW_TRANSACTIONS,
  ],
};

export const PAGE_SIZE = 20;

export const DATE_FORMATS = {
  DISPLAY: 'MMM dd, yyyy',
  DISPLAY_WITH_TIME: 'MMM dd, yyyy HH:mm',
  API: 'yyyy-MM-dd',
  API_WITH_TIME: 'yyyy-MM-dd HH:mm:ss',
} as const;
